-- Create the databases
CREATE DATABASE IF NOT EXISTS `${DB_NAME}`;
CREATE DATABASE IF NOT EXISTS `${DB_NAME_TEST}`;

-- Create users and grant them privileges
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${DB_USER_ADMIN}'@'%' IDENTIFIED BY '${DB_PASSWORD_ADMIN}';

-- Grant privileges
GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO '${DB_USER_ADMIN}'@'%';
GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO '${DB_USER}'@'%';

GRANT ALL PRIVILEGES ON `${DB_NAME_TEST}`.* TO '${DB_USER_ADMIN}'@'%';
GRANT ALL PRIVILEGES ON `${DB_NAME_TEST}`.* TO '${DB_USER}'@'%';

FLUSH PRIVILEGES;

-- Change the password for the root user
ALTER USER 'root'@'localhost' IDENTIFIED BY '${DB_ROOT_PASSWORD}';